package middleware

import (
	"bytes"
	"context"
	"encoding/json"
	"log"
	"net"
	"net/http"
	"time"

	"headsntails-core/config"
	ratelimitv1 "headsntails-core/proto/ratelimit/v1"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
)

// RateLimiterStrategy abstracts the outbound transport layer (HTTP vs gRPC)
type RateLimiterStrategy interface {
	IsAllowed(ctx context.Context, reqBody *RateCheckRequest) bool
}

// RateCheckRequest matches the Pydantic V2 model expected by Phase 1
type RateCheckRequest struct {
	AccessKey *string `json:"access_key,omitempty"`
	IPKey     string  `json:"ip_key"`
	Limit     *int    `json:"limit,omitempty"`
	Window    *int    `json:"window,omitempty"`
}

// RateCheckSuccessResponse maps to the 200 OK structural output from Phase 1
type RateCheckSuccessResponse struct {
	Status       string `json:"status"` // E.g., "allowed"
	CurrentCount int    `json:"current_count"`
	Limit        int    `json:"limit"`
	Remaining    int    `json:"remaining"`
	Message      string `json:"message,omitempty"`
}

// FastAPIErrorResponse captures the native structural wrapper generated by HTTPException
type FastAPIErrorResponse struct {
	Detail json.RawMessage `json:"detail"`
}

// RateLimiterErrorDetail maps the internal 429 error structure from Phase 1
type RateLimiterErrorDetail struct {
	Message      string `json:"message" example:"Rate limit exceeded"`
	CurrentCount int    `json:"current_count" example:"11"`
	Limit        int    `json:"limit" example:"10"`
}

// RateCheck429Response maps the native FastAPI HTTPException structure for a 429 status
type RateCheck429Response struct {
	Detail RateLimiterErrorDetail `json:"detail"`
}

// RateCheck400Response maps the native FastAPI HTTPException structure for a 400 status
type RateCheck400Response struct {
	Detail string `json:"detail" example:"Token-authenticated requests must explicitly supply limit and window metrics."`
}

// ────────────────────────────────────────────────────────
// 1. CORE DOMAIN EVALUATOR (Pure Go Function)
// ────────────────────────────────────────────────────────

// EvaluateRateLimit centralizes payload construction and config overrides.
// It is completely protocol-agnostic and relies purely on basic Go types.
func EvaluateRateLimit(ctx context.Context, strategy RateLimiterStrategy, cfg *config.Config, ipKey string, accessKey *string) bool {
	reqPayload := &RateCheckRequest{
		AccessKey: accessKey,
		IPKey:     ipKey,
	}

	// Apply config defaults when an access key is present
	if reqPayload.AccessKey != nil {
		limit := cfg.TokenBasedRateLimit
		window := cfg.TokenBasedRateLimitWindow
		reqPayload.Limit = &limit
		reqPayload.Window = &window
	}

	return strategy.IsAllowed(ctx, reqPayload)
}

// ────────────────────────────────────────────────────────
// 2. INGRESS ADAPTERS (HTTP Middleware & gRPC Interceptor)
// ────────────────────────────────────────────────────────

// ResolveClientIP sanitizes and extracts the public edge IP passed explicitly by upstream gateways
func ResolveClientIP(r *http.Request) string {
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		parts := bytes.Split([]byte(xff), []byte(","))
		if len(parts) > 0 {
			return string(bytes.TrimSpace(parts[0]))
		}
	}
	if ip, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return ip
	}
	return r.RemoteAddr
}

// RateLimitGuard creates the HTTP middleware layer
func RateLimitGuard(strategy RateLimiterStrategy, executionTimeout time.Duration, cfg *config.Config) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var accessKeyPtr *string
			if aud, ok := r.Context().Value(ContextAudienceKey).(string); ok && aud != "" {
				accessKeyPtr = &aud
			}

			ipKey := ResolveClientIP(r)

			limiterCtx, cancel := context.WithTimeout(r.Context(), executionTimeout)
			defer cancel()

			if !EvaluateRateLimit(limiterCtx, strategy, cfg, ipKey, accessKeyPtr) {
				http.Error(w, "Too Many Requests: Rate limit exceeded or quota exhausted.", http.StatusTooManyRequests)
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

// ResolveGRPCClientIP extracts the client IP address from gRPC metadata or socket peer info
func ResolveGRPCClientIP(ctx context.Context) string {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		if xff := md.Get("x-forwarded-for"); len(xff) > 0 && xff[0] != "" {
			parts := bytes.Split([]byte(xff[0]), []byte(","))
			if len(parts) > 0 {
				return string(bytes.TrimSpace(parts[0]))
			}
		}
	}

	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		if ip, _, err := net.SplitHostPort(p.Addr.String()); err == nil {
			return ip
		}
		return p.Addr.String()
	}

	return "unknown"
}

// RateLimitUnaryInterceptor creates the gRPC unary server interceptor
func RateLimitUnaryInterceptor(strategy RateLimiterStrategy, executionTimeout time.Duration, cfg *config.Config) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		var accessKeyPtr *string
		if aud, ok := ctx.Value(ContextAudienceKey).(string); ok && aud != "" {
			accessKeyPtr = &aud
		}

		ipKey := ResolveGRPCClientIP(ctx)

		limiterCtx, cancel := context.WithTimeout(ctx, executionTimeout)
		defer cancel()

		if !EvaluateRateLimit(limiterCtx, strategy, cfg, ipKey, accessKeyPtr) {
			return nil, status.Error(codes.ResourceExhausted, "Rate limit exceeded or quota exhausted.")
		}

		return handler(ctx, req)
	}
}

// ────────────────────────────────────────────────────────
// 3. OUTBOUND STRATEGY IMPLEMENTATIONS (HTTP & gRPC)
// ────────────────────────────────────────────────────────

type HTTPRateLimiter struct {
	httpClient  *http.Client
	endpointURL string
}

func NewHTTPRateLimiter(endpointURL string, timeout time.Duration) *HTTPRateLimiter {
	return &HTTPRateLimiter{
		endpointURL: endpointURL,
		httpClient: &http.Client{
			Timeout: timeout,
			Transport: &http.Transport{
				Proxy: http.ProxyFromEnvironment,
				DialContext: (&net.Dialer{
					Timeout:   10 * time.Millisecond,
					KeepAlive: 30 * time.Second,
				}).DialContext,
				MaxIdleConns:          100,
				MaxIdleConnsPerHost:   100,
				IdleConnTimeout:       90 * time.Second,
				TLSHandshakeTimeout:   15 * time.Millisecond,
				ExpectContinueTimeout: 1 * time.Second,
			},
		},
	}
}

func (h *HTTPRateLimiter) IsAllowed(ctx context.Context, reqBody *RateCheckRequest) bool {
	payload, err := json.Marshal(reqBody)
	if err != nil {
		log.Printf("[RATE-LIMITER-HTTP] Error marshaling request payload: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}

	internalCtx, cancel := context.WithTimeout(context.Background(), 150*time.Millisecond)
	defer cancel()

	req, err := http.NewRequestWithContext(internalCtx, http.MethodPost, h.endpointURL, bytes.NewBuffer(payload))
	if err != nil {
		log.Printf("[RATE-LIMITER-HTTP] Error creating HTTP request context: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := h.httpClient.Do(req)
	if err != nil {
		log.Printf("[RATE-LIMITER-HTTP] Request failed or timed out: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}
	defer resp.Body.Close()

	// Handle 200 OK Path
	if resp.StatusCode == http.StatusOK {
		var successResp RateCheckSuccessResponse
		if err := json.NewDecoder(resp.Body).Decode(&successResp); err != nil {
			log.Printf("[RATE-LIMITER-HTTP] Error decoding 200 OK success payload: %v. Defaulting to FAIL-OPEN.", err)
			return true
		}
		return successResp.Status == "allowed"
	}

	// Handle Explicit 429 Too Many Requests Blocking Status
	if resp.StatusCode == http.StatusTooManyRequests {
		var errResp FastAPIErrorResponse
		if err := json.NewDecoder(resp.Body).Decode(&errResp); err == nil {
			log.Printf("[RATE-LIMITER-HTTP] Blocked: 429 Rate Limit Exceeded. Detail Matrix: %s", string(errResp.Detail))
		} else {
			log.Printf("[RATE-LIMITER-HTTP] Blocked: 429 Rate Limit Exceeded (Failed to parse detail metadata payload).")
		}
		return false
	}

	var errResp FastAPIErrorResponse
	if err := json.NewDecoder(resp.Body).Decode(&errResp); err == nil {
		log.Printf("[RATE-LIMITER-HTTP] Alert: Upstream returned HTTP status %d. Detail: %s. Defaulting to FAIL-OPEN.", resp.StatusCode, string(errResp.Detail))
	} else {
		log.Printf("[RATE-LIMITER-HTTP] Alert: Upstream returned HTTP status %d. Defaulting to FAIL-OPEN.", resp.StatusCode)
	}

	return true
}

type GRPCRateLimiter struct {
	grpcClient ratelimitv1.RateLimiterServiceClient
}

func NewGRPCRateLimiter(cc grpc.ClientConnInterface) *GRPCRateLimiter {
	return &GRPCRateLimiter{
		grpcClient: ratelimitv1.NewRateLimiterServiceClient(cc),
	}
}

func (g *GRPCRateLimiter) IsAllowed(ctx context.Context, reqBody *RateCheckRequest) bool {
	protoReq := &ratelimitv1.IsAllowedRequest{
		IpKey: reqBody.IPKey,
	}

	if reqBody.AccessKey != nil {
		protoReq.AccessKey = reqBody.AccessKey
	}

	if reqBody.Limit != nil {
		limitVal := int32(*reqBody.Limit)
		protoReq.Limit = &limitVal
	}

	if reqBody.Window != nil {
		windowVal := int32(*reqBody.Window)
		protoReq.Window = &windowVal
	}

	internalCtx, cancel := context.WithTimeout(context.Background(), 150*time.Millisecond)
	defer cancel()

	res, err := g.grpcClient.IsAllowed(internalCtx, protoReq)
	if err != nil {
		log.Printf("[RATE-LIMITER-GRPC] RPC call failed or timed out: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}

	if res.Status == "blocked" {
		return false
	}

	return true
}
